
cd %PROJECT_DIR%
mkdir build
cd build

cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Debug -DEXPORT_TEST=ON -DBUILD_TOOLS=ON -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_PREFIX_PATH=%QT_DIR% %PROJECT_DIR%
start %PROJECT_NAME%.sln
cd %PROJECT_DIR%
